//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBox_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductEntity()
        {
            this.ProductAditionals = new HashSet<ProductAditionalEntity>();
        }
    
        public long ID_Product { get; set; }
        public long ID_Provider { get; set; }
        public long ID_ProductCategory { get; set; }
        public string TX_Name { get; set; }
        public string TX_Description { get; set; }
        public decimal NU_Price { get; set; }
        public decimal NU_ShippingCost { get; set; }
        public bool BO_SpecialOffer { get; set; }
        public bool BO_Service { get; set; }
        public byte[] IM_Image { get; set; }
        public Nullable<bool> BO_Active { get; set; }
        public Nullable<System.DateTime> DT_Register { get; set; }
    
        public virtual ProductCategoryEntity ProductCategory { get; set; }
        public virtual ProviderEntity Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAditionalEntity> ProductAditionals { get; set; }
    }
}
