//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBox_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TheBoxEntities : DbContext
    {
        public TheBoxEntities()
            : base("name=TheBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserEntity> UserEntities { get; set; }
        public virtual DbSet<ProductCategoryEntity> ProductCategoryEntities { get; set; }
        public virtual DbSet<ProviderEntity> ProviderEntities { get; set; }
        public virtual DbSet<ProductEntity> ProductEntities { get; set; }
        public virtual DbSet<AditionalEntity> AditionalEntities { get; set; }
        public virtual DbSet<ProductAditionalEntity> ProductAditionalEntities { get; set; }
        public virtual DbSet<CreditCardEntity> CreditCardEntities { get; set; }
    
        public virtual ObjectResult<string> GetProductNamesByText(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetProductNamesByText", textParameter);
        }
    
        public virtual ObjectResult<ProductEntity> SP_GetProductsByLocation(string text, Nullable<double> latitud, Nullable<double> longitud, Nullable<long> idProvider)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var latitudParameter = latitud.HasValue ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(double));
    
            var longitudParameter = longitud.HasValue ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(double));
    
            var idProviderParameter = idProvider.HasValue ?
                new ObjectParameter("idProvider", idProvider) :
                new ObjectParameter("idProvider", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductEntity>("SP_GetProductsByLocation", textParameter, latitudParameter, longitudParameter, idProviderParameter);
        }
    
        public virtual ObjectResult<ProductEntity> SP_GetProductsByLocation(string text, Nullable<double> latitud, Nullable<double> longitud, Nullable<long> idProvider, MergeOption mergeOption)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var latitudParameter = latitud.HasValue ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(double));
    
            var longitudParameter = longitud.HasValue ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(double));
    
            var idProviderParameter = idProvider.HasValue ?
                new ObjectParameter("idProvider", idProvider) :
                new ObjectParameter("idProvider", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductEntity>("SP_GetProductsByLocation", mergeOption, textParameter, latitudParameter, longitudParameter, idProviderParameter);
        }
    }
}
