//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBoxApp_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long ID_Address { get; set; }
        public long ID_User { get; set; }
        public string TX_FullName { get; set; }
        public string TX_AddressLine1 { get; set; }
        public string TX_AddressLine2 { get; set; }
        public int ID_Country { get; set; }
        public long ID_City { get; set; }
        public string TX_StateProvinceRegion { get; set; }
        public string TX_Zip { get; set; }
        public string TX_PhoneNumber { get; set; }
        public System.DateTime DT_Register { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
