//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBoxApp_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance
    {
        public long ID_Distance { get; set; }
        public long ID_Provider { get; set; }
        public decimal NU_MinDistance { get; set; }
        public decimal NU_MaxDistance { get; set; }
        public int NU_Time { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
