//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBoxApp_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAditional
    {
        public long ID_ProductAditional { get; set; }
        public long ID_Product { get; set; }
        public long ID_Aditional { get; set; }
        public decimal NU_AditionalCost { get; set; }
        public bool BO_Mandatory { get; set; }
        public bool BO_Active { get; set; }
        public Nullable<System.DateTime> DT_Register { get; set; }
    
        public virtual Aditional Aditional { get; set; }
        public virtual Product Product { get; set; }
    }
}
